name: Add Label

on:
  pull_request:

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1.1
        with:
          labels: |
            test:journey:oea-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
