name: Add Label

on:
  pull_request:

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: christianvuerings/add-labels@v1.1
        with:
          labels: |
            test:journey:oea-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Invoke workflow with inputs
        id: workflow_dispatch
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: manual-json-input.yml
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "json_input": "{\n  \"age\": 22,\n  \"hello\": \"world\"\n}" }'
      - name: Workflow dispatch conclusion
        if: success() || failure()
        run: echo Trigger conclusion ${{ steps.workflow_dispatch.outputs.workflow-conclusion }}
