name: 'PR Detect changes'
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled]
    branches:
      - main
jobs:
    job1:
        name: Example Job
        runs-on: ubuntu-latest
        steps:
            #- id: changed_files
            #  name: git-changesets
            #  uses: collin-miller/git-changesets@v1
            #  with:
                  # Default format is 'csv'. Other valid options are 'space-delimited' and 'json'.
            #      format: csv
            #- name: Print steps context output
            #  run: |
            #      echo 'All=${{ steps.changed_files.outputs.all }}'
            #      echo 'Added=${{ steps.changed_files.outputs.added }}'
            #      echo 'Modified=${{ steps.changed_files.outputs.modified }}'
            #      echo 'Removed=${{ steps.changed_files.outputs.removed }}'
            #      echo 'Renamed=${{ steps.changed_files.outputs.renamed }}'
            #      echo 'Added/Modified=${{ steps.changed_files.outputs.added_modified }}'
            - id: changes
              name: Detect PR changes
              uses: fabidick22/detect-changes-action@v2.0.0
              with:
                path: ./
                token: ${{ secrets.GITHUB_TOKEN }}
            - name: Output
              run: |
                  echo 'paths_list=${{ steps.changes.outputs.paths_list }}'
                  echo 'file_list=${{ steps.changes.outputs.file_list }}'
                  echo 'test=${{ fromJSON(steps.changes.outputs.paths_list) }}'